spring:
  config:
    import: optional:file:.env
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
springdoc:
  api-docs:
    version: openapi_3_1

  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
    tags-sorter: alpha
    doc-expansion: none

  cache:
    disabled: true