spring:
  config:
    import: optional:file:.env
    
  datasource:
    url: jdbc:mysql://localhost:3306/yourdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
    tags-sorter: alpha
    doc-expansion: none

  cache:
    disabled: true